# Generated by Django 6.0.1 on 2026-03-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('MANUAL', 'Manual Entry'), ('BULK_IMPORT', 'Bulk Import')], default='QR_CODE', max_length=20)),
                ('qr_code_used', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('scan_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('scan_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['event'], name='attendance_event_i_d7b14a_idx'), models.Index(fields=['user'], name='attendance_user_id_1ea673_idx'), models.Index(fields=['scanned_by'], name='attendance_scanned_7152c9_idx'), models.Index(fields=['event', 'user'], name='attendance_event_i_2a0b08_idx'), models.Index(fields=['user', '-scanned_at'], name='attendance_user_id_0a7c2d_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.TextField(blank=True)),
                ('success', models.BooleanField(db_index=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_logs',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['event'], name='scan_logs_event_i_49c8b5_idx'), models.Index(fields=['user'], name='scan_logs_user_id_519f4d_idx'), models.Index(fields=['success'], name='scan_logs_success_4c4c66_idx'), models.Index(fields=['-attempted_at'], name='scan_logs_attempt_58bc18_idx')],
            },
        ),
    ]
