# Generated by Django 6.0.1 on 2026-09-20 12:00

import apps.seasons.scope
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='season',
            field=models.ForeignKey(blank=True, default=apps.seasons.scope.current_season_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='seasons.season'),
        ),
        migrations.AddField(
            model_name='notification',
            name='season',
            field=models.ForeignKey(blank=True, default=apps.seasons.scope.current_season_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='seasons.season'),
        ),
    ]
