# Generated by Django 6.0.1 on 2026-09-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('ORGANIZER', 'Event Organizer'), ('ADMIN', 'Administrator')], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('section', models.CharField(blank=True, max_length=50)),
                ('is_eligible', models.BooleanField(db_index=True, default=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_roster',
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='IntramuralsTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('qr_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed'), ('DISABLED', 'Disabled')], db_index=True, default='AVAILABLE', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_ticket', to='users.studentroster')),
            ],
            options={
                'db_table': 'intramurals_tickets',
                'indexes': [models.Index(fields=['status', 'ticket_number'], name='intramurals_status_1aa110_idx')],
            },
        ),
    ]
