# Generated by Django 6.0.1 on 2026-09-20 12:00

import apps.seasons.scope
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('users', '0002_alter_user_role_studentroster_intramuralsticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='intramuralsticket',
            name='season',
            field=models.ForeignKey(blank=True, default=apps.seasons.scope.current_season_id, null=True, on_delete=django.db.models.deletion.PROTECT, to='seasons.season'),
        ),
        migrations.AlterField(
            model_name='intramuralsticket',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_tickets', to='users.studentroster'),
        ),
    ]
