# Generated by Django 6.0.1 on 2026-09-19 04:33

from django.conf import settings
from django.db import migrations, models


def validate_existing_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    invalid = []
    queryset = Event.objects.using(schema_editor.connection.alias).annotate(
        reserved=models.Count("registrations", filter=models.Q(
            registrations__status__in=["REGISTERED", "ATTENDED", "NO_SHOW"])))
    for event in queryset.iterator():
        if (event.capacity < 1 or event.current_registered != event.reserved
                or not 0 <= event.current_registered <= event.capacity
                or event.end_time <= event.start_time
                or (event.registration_opens_at and event.registration_closes_at
                    and event.registration_closes_at <= event.registration_opens_at)):
            invalid.append(event.pk)
            if len(invalid) == 20:
                break
    if invalid:
        raise RuntimeError(
            "Events require data review before constraints can be applied. "
            "Check capacity, times, windows and registration totals for IDs: "
            + ", ".join(map(str, invalid)))


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='event_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('current_registered__gte', 0), ('current_registered__lte', models.F('capacity'))), name='event_registration_bounds'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='event_time_order'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('registration_opens_at__isnull', True), ('registration_closes_at__isnull', True), ('registration_closes_at__gt', models.F('registration_opens_at')), _connector='OR'), name='event_registration_window'),
        ),
    ]
