# Generated by Django 6.0.1 on 2026-09-20 06:38

from django.db import migrations, models
import apps.events.models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.events.models.event_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.events.models.event_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
