# Generated by Django 6.0.1 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_slug_event_event_slug_per_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=True),
        ),
    ]
