# Generated by Django 6.0.1 on 2026-09-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_registration_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('PER_EVENT', 'Per-event check-in'), ('DAILY', 'Daily approval'), ('NONE', 'No attendance required')], default='PER_EVENT', max_length=12),
        ),
    ]
