# Generated by Django 6.0.1 on 2026-09-23 17:36

import apps.events.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_attendance_mode'),
        ('houses', '0004_alter_housestanding_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, max_length=500, upload_to=apps.events.models.event_photo_path)),
                ('members', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.house')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('event', 'house'), name='event_team_house_unique')],
            },
        ),
    ]
