# Generated by Django 6.0.1 on 2026-03-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('context_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user'], name='ai_chat_mes_user_id_e1afcd_idx'), models.Index(fields=['session_id'], name='ai_chat_mes_session_67a785_idx'), models.Index(fields=['user', 'session_id', 'created_at'], name='ai_chat_mes_user_id_e3a700_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reasoning', models.TextField(blank=True)),
                ('viewed', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('user_feedback', models.CharField(blank=True, choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful'), ('IRRELEVANT', 'Irrelevant')], max_length=20, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_batch', models.CharField(blank=True, max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='ai_recommen_user_id_76f9ce_idx'), models.Index(fields=['event'], name='ai_recommen_event_i_4a101d_idx'), models.Index(fields=['-confidence_score'], name='ai_recommen_confide_0044eb_idx'), models.Index(fields=['recommendation_batch'], name='ai_recommen_recomme_4e9f69_idx'), models.Index(fields=['expires_at'], name='ai_recommen_expires_fc7b49_idx')],
                'unique_together': {('user', 'event', 'recommendation_batch')},
            },
        ),
    ]
