# Generated by Django 6.0.1 on 2026-03-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('current_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_participations', models.IntegerField(default=0)),
                ('member_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Houses',
                'db_table': 'houses',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='HouseStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('ANNUAL', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('points_change', models.IntegerField(default=0)),
                ('events_participated', models.IntegerField(default=0)),
                ('events_won', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='houses.house')),
            ],
            options={
                'db_table': 'house_standings',
                'ordering': ['-period_start', 'rank'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='house_stand_period__871023_idx'), models.Index(fields=['rank'], name='house_stand_rank_4c7bc5_idx')],
                'unique_together': {('house', 'period_type', 'period_start')},
            },
        ),
    ]
