# Generated by Django 6.0.1 on 2026-09-20 07:03

import apps.houses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='logo_url',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.houses.models.house_logo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
