# Generated by Django 6.0.1 on 2026-09-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_housestanding_season'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housestanding',
            unique_together={('season', 'house', 'period_type', 'period_start')},
        ),
    ]
