# Generated by Django 6.0.1 on 2026-09-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_link_verified_membership_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9),
        ),
    ]
